---guitars---

INSERT INTO listing(Name, TypeInstrument, Condition, Price, Description, Year, Color, Material)
VALUES 
('Martin Acoustic Guitar', 'Guitar', 'Used', 1500, 'The Martin Acoustic Guitar offers a rich, full-bodied sound and impeccable craftsmanship. Ideal for both casual strumming and professional performances.', 2019, 'Natural', 'Solid Sitka Spruce and Rosewood'),
('Fender Stratocaster Electric Guitar', 'Guitar', 'New', 900, 'Unleash your inner rockstar with the iconic Fender Stratocaster. Its versatile sound and sleek design make it a go-to choice for guitarists across genres.', 2021, 'Sunburst', 'Alder and Maple'),
('Gibson Les Paul Standard', 'Guitar', 'Used', 2000, 'The Gibson Les Paul Standard is a legendary electric guitar known for its powerful tone and iconic design. A favorite among professional musicians.', 2017, 'Heritage Cherry Sunburst', 'Mahogany and Maple'),
('Taylor 814ce Acoustic-Electric Guitar', 'Guitar', 'New', 3500, 'The Taylor 814ce is a high-end acoustic-electric guitar with a superb blend of tone and playability. Perfect for the discerning acoustic guitarist.', 2022, 'Natural', 'Sitka Spruce and Indian Rosewood'),
('Ibanez RG550 Electric Guitar', 'Guitar', 'Used', 800, 'The Ibanez RG550 is a classic shred machine, known for its fast neck and versatile sound. A reliable choice for guitarists who crave speed and precision.', 2015, 'Desert Sun Yellow', 'Basswood and Maple'),
('Fender American Professional II Stratocaster', 'Guitar', 'New', 1500.00, 'The Fender American Professional II Stratocaster is a modern iteration of the classic Strat design, known for its versatile tones and comfortable playability.', NULL, 'Various', 'Alder body, maple neck, rosewood or maple fretboard'),
('Gibson Les Paul Standard ''50s', 'Guitar', 'New', 2500.00, 'The Gibson Les Paul Standard ''50s model pays homage to the iconic Les Paul design of the 1950s, featuring a rich, warm tone and a classic look.', NULL, 'Heritage Cherry Sunburst, Gold Top, etc.', 'Mahogany body, maple top, mahogany neck, rosewood or ebony fretboard'),
('Taylor 214ce Deluxe Grand Auditorium', 'Guitar', 'New', 1500.00, 'The Taylor 214ce Deluxe is an acoustic-electric guitar known for its balanced tone and high-quality construction, making it suitable for a variety of playing styles.', NULL, 'Natural finish', 'Solid Sitka spruce top, layered rosewood back and sides, ebony fretboard'),
('Ibanez RG550 Genesis Collection', 'Guitar', 'New', 1300.00, 'The Ibanez RG550 is a part of the Genesis Collection, known for its sleek design, fast neck, and versatile pickups, making it popular among rock and metal players.', NULL, 'Desert Sun Yellow, Road Flare Red, etc.', 'Basswood body, maple neck, maple or rosewood fretboard'),
('Martin D-28 Acoustic Guitar', 'Guitar', 'New', 3500.00, 'The Martin D-28 is a classic acoustic guitar known for its rich, full-bodied tone and timeless design, making it a favorite among acoustic enthusiasts.', NULL, 'Natural finish', 'Solid Sitka spruce top, East Indian rosewood back and sides, ebony fretboard');