---pianos---

INSERT INTO listing (Name, TypeInstrument, Condition, Price, Description, Year, Color, Material)
VALUES 
('Yamaha Upright Piano', 'Piano', 'Used', 3500, 'This Yamaha Upright Piano is a perfect choice for both beginners and experienced players. Its rich tone and responsive keys make it a joy to play.', 2018, 'Ebony', 'Wood'),
('Steinway Grand Piano', 'Piano', 'New', 12000, 'The Steinway Grand Piano is a masterpiece of craftsmanship and musicality. With its elegant design and unparalleled sound quality, it''s a superb instrument for any pianist.', 2020, 'Mahogany', 'Maple and Spruce'),
('Kawai Digital Piano', 'Piano', 'New', 1200, 'The Kawai Digital Piano combines the feel of an acoustic piano with modern technology. Perfect for those who desire versatility and convenience.', 2022, 'Rosewood', 'Various (Digital components)'),
('Baldwin Baby Grand Piano', 'Piano', 'Used', 8000, 'The Baldwin Baby Grand Piano delivers a classic, rich tone in a compact size. Ideal for those with a passion for traditional elegance.', 2015, 'Walnut', 'Spruce and Mahogany'),
('Casio Privia Digital Piano', 'Piano', 'New', 600, 'The Casio Privia Digital Piano offers affordability without compromising on quality. Packed with features, it''s suitable for beginners and intermediate players.', 2023, 'Black', 'Plastic and Metal'),
('GrandHarmony GH-300', 'Piano', 'New', 12000, 'A professional grand piano with exquisite sound and a sleek ebony finish. Perfect for both classical and modern compositions.', 2023, 'Ebony', 'Wood and metal construction'),
('UprightMelody UM-200', 'Piano', 'Used', 4500, 'A well-maintained upright piano that produces warm tones. Ideal for intermediate players or those looking for a compact yet resonant instrument.', 2018, 'Mahogany', 'Wood and metal construction'),
('DigitalHarbor DH-500', 'Piano', 'New', 2200, 'A modern digital piano with advanced features, weighted keys, and multiple sound options. Perfect for versatile musicians and home studios.', 2023, 'Black', 'Plastic and electronic components'),
('VintageVirtuoso V-88', 'Piano', 'Used', 8000, 'A vintage grand piano with a rich history and unique character. Restored to maintain its original charm while offering timeless performance.', 1965, 'Walnut', 'Wood and metal construction'),
('ConcertoCraft CC-1200', 'Piano', 'New', 25000, 'A concert grand piano designed for professional performances and recording studios. Boasts exceptional tonal quality and precision craftsmanship.', 2023, 'Rosewood', 'Wood and metal construction'),
('Yamaha Grand Piano C3', 'Piano', 'Used', 12000.00, 'This Yamaha Grand Piano C3 is a beautiful instrument with a rich history of performances. Crafted with precision and care, it offers a warm and resonant sound. Some minor cosmetic wear adds character.', 2005, 'Black', 'Spruce soundboard and various hardwoods for the body'),
('Steinway & Sons Model B Concert Grand', 'Piano', 'New', 85000.00, 'Experience the pinnacle of musical excellence with the Steinway & Sons Model B Concert Grand. This brand-new piano boasts unparalleled craftsmanship, delivering a powerful and nuanced sound.', 2022, 'Ebony', 'Hard rock maple, mahogany, spruce, and wool damper felt'),
('Kawai Upright Piano K-300', 'Piano', 'New', 6500.00, 'The Kawai Upright Piano K-300 combines modern design with exceptional playability. This new piano is perfect for both beginners and experienced players.', 2023, 'Polished ebony', 'High-grade composite materials and selected hardwoods'),
('Baldwin Baby Grand Piano R1', 'Piano', 'Used', 9500.00, 'The Baldwin Baby Grand Piano R1 is a timeless classic that has been meticulously cared for. Dating back to 1998, this used piano offers a warm and charming tone.', 1998, 'Cherry wood', 'Hardwood, often maple or birch'),
('Roland Digital Piano RD-2000', 'Piano', 'Used', 2200.00, 'The Roland RD-2000 Digital Piano is a versatile and professional-grade instrument suitable for stage and studio use. This used piano, made in 2019, delivers authentic piano sounds with modern features.', 2019, 'Black', 'Plastic and metal components'),
('Steinway Model D Concert Grand - Vintage 1965', 'Piano', 'Restored (Excellent)', 89999.99, 'This Steinway Model D Concert Grand, crafted in 1965, has been meticulously restored to its former glory. The timeless ebony black finish enhances the grandeur of this iconic piano, making it a centerpiece for both musicians and enthusiasts alike.', NULL, 'Ebony Black', 'Polished Ebony Finish'),
('Yamaha Upright Piano - Classic Walnut (1990)', 'Piano', 'Used (Good)', 2499.99, 'This Yamaha Upright Piano, manufactured in 1990, boasts a warm classic walnut finish. With a solid wood construction, it offers a rich and resonant tone. Perfect for those seeking a reliable instrument with a touch of vintage charm.', 1990, 'Classic Walnut', 'Wood'),
('Kawai Baby Grand - Ivory White (2018)', 'Piano', 'Like New', 12999.99, 'The Kawai Baby Grand, crafted in 2018, is presented in an elegant ivory white. The high-gloss polyester finish not only adds sophistication but also protects the piano''s exquisite craftsmanship. Experience both beauty and precision in this like-new instrument.', 2018, 'Ivory White', 'High-Gloss Polyester Finish'),
('Baldwin Acrosonic Spinet - Mahogany (1975)', 'Piano', 'Refurbished', 1799.99, 'The Baldwin Acrosonic Spinet, originating from 1975, features a timeless mahogany color with a wood veneer finish. This refurbished spinet piano is perfect for those who appreciate vintage aesthetics and space-saving design.', 1975, 'Mahogany', 'Wood Veneer'),
('Roland Digital Grand Piano - Contemporary Black (2021)', 'Piano', 'Brand New', 5499.99, 'The Roland Digital Grand Piano, introduced in 2021, offers cutting-edge technology with a sleek contemporary black design. Crafted from high-quality composite and metal materials, this brand new digital piano combines modern aesthetics with advanced features for the discerning musician.', 2021, 'Contemporary Black', 'Composite and Metal');