INSERT INTO listing(Name, TypeInstrument, Condition, Price, Description, Year, Color, Material) 
VALUES 
('Stradivarius Model Violin', 'Violin', 'Used', 20000.00, 'This Stradivarius Model Violin is a vintage instrument with a rich and resonant tone. Crafted with precision and attention to detail, it has been played over the years, acquiring a warm character.', 1906, 'Aged varnish', 'Traditional wood'),
('Yamaha Concert Series Violin', 'Violin', 'New', 1500.00, 'The Yamaha Concert Series Violin is a brand-new instrument designed for both beginners and experienced players. It offers a clear and bright tone with easy playability.', 2023, 'Classic amber varnish', 'High-quality wood'),
('Stentor Student Violin', 'Violin', 'New', 300.00, 'The Stentor Student Violin is an excellent choice for beginners. This new violin provides a balanced and focused sound, making it ideal for those starting their musical journey.', 2023, 'Reddish-brown varnish', 'Quality wood'),
('Antique German Violin', 'Violin', 'Used', 2500.00, 'This Antique German Violin carries the history of generations. Crafted in the late 19th century, it exhibits a warm, mature tone. While showing signs of use, it remains in good condition.', 1889, 'Traditional golden-brown varnish', 'Vintage wood'),
('Carbon Fiber Professional Violin', 'Violin', 'New', 1800.00, 'The Carbon Fiber Professional Violin is a modern masterpiece. Built with innovative materials, it offers a powerful and clear sound. Perfect for professional musicians seeking a contemporary edge.', 2023, 'Sleek black carbon fiber', 'Carbon fiber and modern components'),
('Stradivarius Replica - Vintage 1735', 'Violin', 'Collector''s Item (Excellent)', 25000.00, 'This Stradivarius Replica violin, modeled after the iconic 1735 design, is a collector''s dream. Crafted with aged maple and spruce, it boasts an antique brown finish that exudes timeless elegance. The instrument is in excellent condition, showcasing the superb craftsmanship of a bygone era.', 1998, 'Antique Brown', 'Aged Maple and Spruce'),
('Stradivarius Violin', 'Violin', 'Used', 25000, 'Own a piece of history with this Stradivarius Violin. Crafted with precision and attention to detail, it produces a warm, resonant tone that is unmatched.', 1730, 'Amber', 'Spruce and Maple'),
('Yamaha Electric Violin', 'Violin', 'New', 800, 'Experience the modern side of violin playing with this Yamaha Electric Violin. Perfect for musicians looking to explore different genres with style and versatility.', 2023, 'Blue', 'Carbon Fiber'),
('Stentor Student Violin', 'Violin', 'New', 150, 'The Stentor Student Violin is an excellent choice for beginners. It offers a balanced tone and durability for the aspiring violinist.', 2022, 'Natural', 'Maple and Ebony'),
('Fiddlerman Master Violin', 'Violin', 'Used', 900, 'The Fiddlerman Master Violin is crafted for advanced players seeking a nuanced and powerful sound. Its precise construction ensures a professional playing experience.', 2019, 'Antique Brown', 'Spruce and Maple'),
('Cecilio Electric Violin', 'Violin', 'New', 200, 'The Cecilio Electric Violin is perfect for modern performers. With its sleek design and amplified sound, it''s an excellent choice for stage performances.', 2023, 'Metallic Red', 'Maple and Ebony'),
('SonataStrad S800', 'Violin', 'New', 3500, 'Handcrafted violin with a spruce top, maple back, and ebony fittings. Offers a warm, resonant tone suitable for various musical genres.', 2023, 'Natural', 'Spruce, maple, and ebony'),
('MaestroMelody MM-450', 'Violin', 'Used', 2000, 'Intermediate-level violin with a balanced sound and fine craftsmanship. Perfect for advancing students and casual performers.', 2016, 'Amber', 'Spruce, maple, and ebony'),
('ElectricEnsemble EE-200', 'Violin', 'New', 800, 'Electric violin with built-in pickups for amplified performances. Ideal for musicians exploring contemporary styles and stage presence.', 2023, 'Metallic Blue', 'Synthetic body and electronic components'),
('AntiqueAria AA-120', 'Violin', 'Used', 5000, 'Rare antique violin with a beautifully aged appearance and a mellow, nuanced sound. A collector''s item for discerning musicians.', 1920, 'Antique Brown', 'Spruce, maple, and ebony'),
('VirtuosoVortex V-700', 'Violin', 'New', 6800, 'Professional-grade violin with a bold and powerful tone. Crafted for advanced players and solo performances.', 2023, 'Dark Cherry', 'Spruce, maple, and ebony');
