---drums---

INSERT INTO listing (Name, TypeInstrument, Condition, Price, Description, Year, Color, Material)
VALUES 
('DW Collector''s Series Drum Kit', 'Drums', 'Used', 3000, 'The DW Collector''s Series is a top-tier drum kit with exceptional build quality and tonal versatility. Perfect for drummers who demand the best.', 2020, 'Satin Natural', 'Maple'),
('Roland V-Drums Electronic Drum Set', 'Drums', 'New', 1500, 'Experience the future of drumming with the Roland V-Drums. This electronic drum set offers realistic sounds and endless creative possibilities for modern drummers.', 2021, 'Black', 'Various (Electronic components)'),
('Pearl Export Series Drum Kit', 'Drums', 'Used', 800, 'The Pearl Export Series Drum Kit is a reliable choice for drummers of all levels. Known for its durability and balanced sound, it''s a great investment.', 2016, 'Midnight Blue', 'Poplar'),
('Mapex Saturn V Drum Kit', 'Drums', 'New', 2200, 'The Mapex Saturn V Drum Kit is a professional-grade set with a perfect blend of warmth and projection. Ideal for studio sessions and stage performances.', 2022, 'Vintage Sparkle', 'Maple and Walnut'),
('Gretsch Catalina Club Jazz Drum Kit', 'Drums', 'Used', 1000, 'The Gretsch Catalina Club Jazz Drum Kit is a compact and versatile set with a focus on classic jazz tones. Perfect for intimate performances and recording.', 2015, 'Satin Antique Burst', 'Mahogany and Poplar'),
('RhythmRider RR-500', 'Drums', 'New', 1000, 'Entry-level drum kit with poplar shells and basic hardware. Suitable for beginners and practice sessions.', 2023, 'Midnight Blue', 'Poplar'),
('GrooveMaster GM-800', 'Drums', 'Used', 1800, 'Intermediate-level drum set with birch shells and upgraded hardware. Perfect for gigging musicians and recording sessions.', 2015, 'Red Sparkle', 'Birch'),
('StudioSculpt SS-1200', 'Drums', 'New', 3500, 'Professional studio drum kit with maple shells and precision hardware. Designed for studio recording and live performances.', 2023, 'Natural Satin', 'Maple'),
('VintageVibe VV-300', 'Drums', 'Used', 2200, 'Vintage drum set with mahogany shells and classic hardware. A collector''s item with a warm and rich sound.', 1972, 'Antique White', 'Mahogany'),
('FusionFury FF-600', 'Drums', 'New', 4000, 'Versatile fusion drum kit with hybrid shells (maple and acrylic) and advanced hardware. Ideal for drummers exploring various styles.', 2023, 'Transparent Blue', 'Maple and acrylic'),
('DW Collector''s Series Drum Kit', 'Drum', 'New', 5000.00, 'The DW Collector''s Series Drum Kit is a flagship professional drum set known for its exceptional sound quality and craftsmanship. This brand-new kit offers versatility and precision for drummers seeking top-tier performance.', 2023, 'Custom finish options available', 'Maple, Birch, or Cherry shells, various hardware options'),
('Pearl Export Series Drum Set', 'Drum', 'Used', 800.00, 'The Pearl Export Series Drum Set is a reliable and popular choice among drummers. This used drum kit, although showing signs of wear, delivers a balanced and punchy sound suitable for various musical styles.', 2015, 'Jet Black', 'Poplar and Asian mahogany shells, steel hardware'),
('Tama Imperialstar 5-Piece Drum Kit', 'Drum', 'New', 900.00, 'The Tama Imperialstar 5-Piece Drum Kit offers excellent value and quality for beginners and intermediate drummers. This new kit provides durability and good sound projection.', 2023, 'Vintage Blue Sparkle', 'Poplar shells, steel hardware'),
('Ludwig Classic Maple Drum Set', 'Drum', 'Used', 2500.00, 'The Ludwig Classic Maple Drum Set is a vintage kit known for its warm and resonant tone. This used drum set from the 1980s offers a classic sound sought after by many drumming enthusiasts.', 1985, 'Natural Maple', 'Maple shells, chrome hardware'),
('Mapex Saturn Evolution Series Drum Kit', 'Drum', 'New', 1200.00, 'The Mapex Saturn Evolution Series Drum Kit is a versatile and modern drum set suitable for various genres. This brand-new kit boasts a powerful sound and sleek design.', 2023, 'Transparent Cherry', 'Maple and walnut hybrid shells, chrome hardware'),
('Gretsch Catalina Club Jazz Drum Set', 'Drum', 'Used', 600.00, 'The Gretsch Catalina Club Jazz Drum Set is a compact and versatile kit perfect for smaller venues and jazz performances. This used drum set, although older, offers a warm and focused sound.', 2010, 'Satin Antique Fade', 'Mahogany shells, chrome hardware');